
---
#
# Installing logstash
#

# Add APT repository
- name: Adding logstash APT repository
  apt_repository:
    repo: deb http://packages.elastic.co/logstash/2.3/debian stable main
    state: present

# Installing logstash
- name: Update repositories cache and install Elasticsearch
  apt:
    name: logstash
    update_cache: yes

# Creating directories for SSL
- name: Creates SSL directories
  file: path=/etc/pki/tls/certs state=directory

- name: Creates SSL directories
  file: path=/etc/pki/tls/private state=directory

- name: Updating the config file to restrict outside access
  lineinfile:
    destfile: /etc/ssl/openssl.cnf
    regexp: 'subjectAltName ='
    line: 'subjectAltName = IP: {{ ansible_eth0.ipv4.address }}'

- name: Generate SSL certificates
  shell: cd /etc/pki/tls

- name: Generate SSL certificates
  shell: openssl req -config /etc/ssl/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt


- name: Configure Beats configuration file
  template:
    src=beats-input.conf.j2
    dest=/etc/logstash/conf.d/02-beats-input.conf
    owner=root
    group=root
    mode=0644


- name: Configure Syslog Filter
  template:
    src=syslog-filter.conf.j2
    dest=/etc/logstash/conf.d/10-syslog-filter.conf
    owner=root
    group=root
    mode=0644


- name: Configure Elasticsearch output file
  template:
    src=elasticsearch-output.conf.j2
    dest=/etc/logstash/conf.d/30-elasticsearch-output.conf
    owner=root
    group=root
    mode=0644


# start nginx service
- name: Starting Logstash
  systemd:
    name: logstash
    state: reloaded
    daemon_reload: yes

# start nginx service
- name: Starting Logstash
  systemd:
    name: logstash
    enabled: yes
