
---
#
# Installing Nginx
#

- name: Update repositories cache and install Kibana
  apt:
    name: nginx
    update_cache: yes

# create /etc/nginx/conf.d/ directory
- name: Create nginx directory structure
  file: path=/etc/nginx/conf.d/
    state=directory
    mode=0755

# deploy kibana.conf with FQDN
- name: Setup nginx reverse proxy for kibana
  template:
    src=kibana.conf.j2
    dest=/etc/nginx/conf.d/kibana.conf
    owner=root
    group=root
    mode=0644
  register: nginx_needs_restart

# deploy basic nginx.conf 8080 vhost
- name: Setup nginx TCP/8080 vhost for SSL certificate
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644

# start nginx service
- name: Enabling Nginx
  systemd:
    name: nginx
    state: started
    daemon_reload: yes


- name: Check if nginx is in use
  shell: systemctl is-enabled nginx.service | egrep -qv 'masked|disabled'
  register: nginx_in_use
  ignore_errors: yes
  tags:
    # Skip ANSIBLE0012 Commands should not change things if nothing needs doing
    # Determine if nginx is enabled
    - skip_ansible_lint

- name: Enabling Nginx
  systemd:
    name: nginx
    enabled: yes
