
---
#
# Installing Nginx
#

- name: Update repositories cache and install Kibana
  apt:
    name: nginx
    update_cache: yes

# create /etc/nginx/conf.d/ directory
- name: Create nginx directory structure
  file: path=/etc/nginx/conf.d/
    state=directory
    mode=0755

# deploy kibana.conf with FQDN
- name: Setup Nginx reverse proxy for kibana
  template:
    src=kibana.conf.j2
    dest=/etc/nginx/sites-available/default
    owner=root
    group=root
    mode=0644
  register: nginx_needs_restart

# deploy basic nginx.conf 8080 vhost
#- name: Setup nginx TCP/8080 vhost for SSL certificate
#  template:
#    src=nginx.conf.j2
#    dest=/etc/nginx/nginx.conf
#    owner=root
#    group=root
#    mode=0644

# Enable nginx service
- name: Enabling Nginx
  systemd:
    name: nginx
    enabled: yes

# start nginx service
- name: Starting Nginx
  systemd:
    name: nginx
    state: started
    daemon_reload: yes


- name: Check kibana users
  stat: path=/etc/nginx/htpasswd.users
  ignore_errors: true
  register: kibana_user_pwfile_exists


- name: Create kibana admin user
  command: htpasswd -b -c /etc/nginx/htpasswd.users {{kibana_user}} {{kibana_password}}
  ignore_errors: true
  when: kibana_user_pwfile_exists != 0

# start nginx service
- name: Starting Nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes
